# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in this directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in this directory
    directory: "/compose/production/dserver_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    # Look for `requirements.txt` in this directory
    directory: "/compose/production/dserver_client"
    schedule:
      interval: "weekly"
