name: dtool-lookup-client-container-image-build-and-test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pip-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pip-tools and pipdeptree
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install pip-tools
          pip install pipdeptree
          
      - name: Requirements inspection and upgrade
        run: |
          cd compose/production/dtool_lookup_client
          echo "### Initial pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Initial pipdeptree ###"
          pipdeptree | tee pipdeptree.initial
          echo "### pip-compile --upgrade ###"
          pip-compile --upgrade requirements.in
          echo "### requirements.txt diff ###"
          git diff requirements.txt | tee diff_requirements.txt
          echo "### Repeated pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Upgraded pipdeptree ###"
          pipdeptree | tee pipdeptree.upgraded

  build-and-test:
    uses: jotelha/dtool-framework-workflows/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml@master
    with:
      image: jotelha/dtool-lookup-client
      service: dtool_lookup_clinet
      docker_file: ./compose/production/dtool_lookup_client/Dockerfile
